//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace monovitez.DAL.HelperClasses
{
	/// <summary>Field Creation Class for entity VehicleMakeEntity</summary>
	public partial class VehicleMakeFields
	{
		/// <summary>Creates a new VehicleMakeEntity.Abrv field instance</summary>
		public static EntityField2 Abrv { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VehicleMakeFieldIndex.Abrv); }}
		/// <summary>Creates a new VehicleMakeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VehicleMakeFieldIndex.Id); }}
		/// <summary>Creates a new VehicleMakeEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VehicleMakeFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity VehicleModelEntity</summary>
	public partial class VehicleModelFields
	{
		/// <summary>Creates a new VehicleModelEntity.Abrv field instance</summary>
		public static EntityField2 Abrv { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VehicleModelFieldIndex.Abrv); }}
		/// <summary>Creates a new VehicleModelEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VehicleModelFieldIndex.Id); }}
		/// <summary>Creates a new VehicleModelEntity.MakeId field instance</summary>
		public static EntityField2 MakeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VehicleModelFieldIndex.MakeId); }}
		/// <summary>Creates a new VehicleModelEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VehicleModelFieldIndex.Name); }}
	}
	

}