//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using monovitez.DAL.FactoryClasses;
using monovitez.DAL.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace monovitez.DAL.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitVehicleMakeEntityInfo();
			InitVehicleModelEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits VehicleMakeEntity's info objects</summary>
		private void InitVehicleMakeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(VehicleMakeFieldIndex), "VehicleMakeEntity");
			this.AddElementFieldInfo("VehicleMakeEntity", "Abrv", typeof(System.String), false, false, false, true,  (int)VehicleMakeFieldIndex.Abrv, 10485760, 0, 0);
			this.AddElementFieldInfo("VehicleMakeEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)VehicleMakeFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("VehicleMakeEntity", "Name", typeof(System.String), false, false, false, true,  (int)VehicleMakeFieldIndex.Name, 10485760, 0, 0);
		}

		/// <summary>Inits VehicleModelEntity's info objects</summary>
		private void InitVehicleModelEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(VehicleModelFieldIndex), "VehicleModelEntity");
			this.AddElementFieldInfo("VehicleModelEntity", "Abrv", typeof(System.String), false, false, false, true,  (int)VehicleModelFieldIndex.Abrv, 10485760, 0, 0);
			this.AddElementFieldInfo("VehicleModelEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)VehicleModelFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("VehicleModelEntity", "MakeId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)VehicleModelFieldIndex.MakeId, 0, 0, 10);
			this.AddElementFieldInfo("VehicleModelEntity", "Name", typeof(System.String), false, false, false, true,  (int)VehicleModelFieldIndex.Name, 10485760, 0, 0);
		}
	}
}