//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace monovitez.DAL.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitVehicleMakeEntityMappings();
			InitVehicleModelEntityMappings();
		}

		/// <summary>Inits VehicleMakeEntity's mappings</summary>
		private void InitVehicleMakeEntityMappings()
		{
			this.AddElementMapping("VehicleMakeEntity", @"ixyvvjne", @"public", "VehicleMake", 3, 0);
			this.AddElementFieldMapping("VehicleMakeEntity", "Abrv", "Abrv", true, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("VehicleMakeEntity", "Id", "Id", false, "Integer", 0, 10, 0, true, "public.VehicleMake_Id_seq", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("VehicleMakeEntity", "Name", "Name", true, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits VehicleModelEntity's mappings</summary>
		private void InitVehicleModelEntityMappings()
		{
			this.AddElementMapping("VehicleModelEntity", @"ixyvvjne", @"public", "VehicleModel", 4, 0);
			this.AddElementFieldMapping("VehicleModelEntity", "Abrv", "Abrv", true, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("VehicleModelEntity", "Id", "Id", false, "Integer", 0, 10, 0, true, "public.VehicleModel_Id_seq", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("VehicleModelEntity", "MakeId", "MakeId", true, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("VehicleModelEntity", "Name", "Name", true, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 3);
		}

	}
}
